### ISSUE TITLE
Regaining quests are run together during the same campaign

### ISSUE THREAD

**Issue by schofida** [schofida/CWORR#18]
![image](https://user-images.githubusercontent.com/14967936/226152041-192edf08-3116-46c0-90ec-2638cc6db9ab.png)
![image](https://user-images.githubusercontent.com/14967936/226152051-0a3bb99c-a5ed-4970-831c-756e84673da8.png)

this visual glitch occurs when you lose all holds other than solitude after you get reunification of skyrim also occurs with skirmish and mine and farm quests

(an addition qol change could be to deactivate the waypoints for town,fort,mine and mills etc when a battle for them occurs)

**Comment by schofida** [comment]
@LABWAZHERE This is strange and potentially bad. Can I see the CWO Debug screen while this is appearing? Every campaign should be offense/defense of one hold at a time.

**Comment by LABWAZHERE** [comment]
![20230319144031_1](https://user-images.githubusercontent.com/128126252/226152309-4ec6f321-71ea-45c1-b42d-1228a7057773.jpg)

**Comment by LABWAZHERE** [comment]
update: fresh save, still occurred, only with Morthal after skirmish at stonehills. it triggered reunification of skyrim, could that be causing it?
![20230319222241_1](https://user-images.githubusercontent.com/128126252/226172716-21c72772-26c9-4e09-a67d-e8d613584c6b.jpg)

**Comment by schofida** [comment]
couple of other things, concurrent sieges still occured
![20230401111344_1](https://user-images.githubusercontent.com/128126252/229261049-eb53f8c1-d151-4561-9bad-935e4818fe2c.jpg)
This happened (dancing objective marker)
![20230401111412_2](https://user-images.githubusercontent.com/128126252/229261063-f173c608-9006-4d89-9830-a1fb5a658d49.jpg)
![20230401111413_1](https://user-images.githubusercontent.com/128126252/229261064-c9e7cc2d-77c0-423b-8124-fb30cdadbcf2.jpg)
![20230401111413_2](https://user-images.githubusercontent.com/128126252/229261057-30dfdf20-438b-4905-8bfe-f3c786691dfb.jpg)
![20230401111412_1](https://user-images.githubusercontent.com/128126252/229261062-fb988f20-03ca-4e3c-a840-d2cd47704c58.jpg)
and liberate markarth quest popped up after winning stonehills (happened a second time as well)

_Originally posted by @LABWAZHERE in https://github.com/schofida/CWORR/issues/12#issuecomment-1492794698_

**Comment by ds-nscorp** [comment]
So this issue I am still unsure of how you got this to happen. In all of my testing I have never seen this.

So I am not sure if you use Mod organizer or not, but I snuck an INI override into the mod folder. It should turn Papyrus (Skyrim's scripting engine) logging on. Mod Organizer has a feature to allow mods to tweak ini settings so it should 'Just Work'.

If it did, in your My Documents\My Games\ folder, next to you Saves folder, there should hopefully also be a logs folder. If there is, can you zip up the folder and attach to this issue?

**Comment by LABWAZHERE** [comment]
i use vortex and i have no clue how to use papyrus on vortex and i have so many mods that moving over to MO would be a nightmare (tried once, never again) i may try to convert them but i have 100 something mods soooooo.......


on another note i have a theory on this myself (coming from an uneducated person) my theory is this is leftover code from conquest (disabled it but idk), this theory has some credit as in conquest when you attack forts you hear a horn being played and i heard one when i got these pictures. but this also is debunked by the fact i never heard it during the fort battles of the most recent update and i haven't uninstalled conquest since then (only disabled)

**Comment by LABWAZHERE** [comment]
could this be leftover code from the base game? since the base game doesn't have the sieges when completing these missions it could be the game thinking it is the base game code and activating the "next" hold

**Comment by schofida** [comment]
I think that I might have gotten to the bottom of this. I will hopefully have fixed in the next release tentatively scheduled for tomorrow evening.

**Comment by LABWAZHERE** [comment]
![20230426182336_1](https://user-images.githubusercontent.com/128126252/234529335-ba46323e-66ad-43b7-b00b-e63961cc0ee5.jpg)
the visual glitch still occurs, yet to determine if regain appears

**Comment by schofida** [comment]
I will close this. Unfortunately you cannot test this on your existing save.

I discovered thanks to you that setting the quest stage to the 'So and So Completed' stage does not automatically clean up the quest objectives so when you get the same quest, those uncompleted objectives are still hanging out there. I made sure to complete/fail all objectives programmatically before stopping the quest. So it should fix the issue going forward but your save will still have those stale objectives unfortunately.

**Comment by LABWAZHERE** [comment]
Issue still persists at least in eves stormcloak save
